import { Product } from "interfaces";

export const dummyProducts: Product[] = [
  {
    id: 0,
    name: "Surface",
    price: 1200,
    imagePath: "https://i.ibb.co/txhwSns/headphones-a-4.webp",
    color: "Black",
    brand: "Microsoft",
  },
  {
    id: 1,
    name: "MacBook Air",
    price: 999,
    imagePath: "https://i.ibb.co/CnzYPw1/headphones-c-1.webp",
    color: "Silver",
    brand: "Apple",
  },
  {
    id: 2,
    name: "Cell Phone",
    price: 800,
    imagePath: "https://i.ibb.co/D7NZDPk/headphones-a-1.webp",
    color: "Black",
    brand: "Samsung",
  },
  {
    id: 3,
    name: "Keyboard",
    price: 50,
    imagePath: "https://i.ibb.co/KzwMh9w/watch-3.webp",
    color: "Black",
    brand: "Microsoft",
  },
  {
    id: 4,
    name: "Mouse",
    price: 10,
    imagePath: "https://i.ibb.co/CQN3cCp/watch-2.webp",
    color: "Black",
    brand: "Microsoft",
  },
  {
    id: 0,
    name: "Surface",
    price: 1200,
    imagePath: "https://i.ibb.co/txhwSns/headphones-a-4.webp",
    color: "Black",
    brand: "Microsoft",
  },
  {
    id: 1,
    name: "MacBook Air",
    price: 999,
    imagePath: "https://i.ibb.co/CnzYPw1/headphones-c-1.webp",
    color: "Silver",
    brand: "Apple",
  },
  {
    id: 2,
    name: "Cell Phone",
    price: 800,
    imagePath: "https://i.ibb.co/D7NZDPk/headphones-a-1.webp",
    color: "Black",
    brand: "Samsung",
  },
  {
    id: 3,
    name: "Keyboard",
    price: 50,
    imagePath: "https://i.ibb.co/KzwMh9w/watch-3.webp",
    color: "Black",
    brand: "Microsoft",
  },
  {
    id: 4,
    name: "Mouse",
    price: 10,
    imagePath: "https://i.ibb.co/CQN3cCp/watch-2.webp",
    color: "Black",
    brand: "Microsoft",
  },
  {
    id: 0,
    name: "Surface",
    price: 1200,
    imagePath: "https://i.ibb.co/txhwSns/headphones-a-4.webp",
    color: "Black",
    brand: "Microsoft",
  },
  {
    id: 1,
    name: "MacBook Air",
    price: 999,
    imagePath: "https://i.ibb.co/CnzYPw1/headphones-c-1.webp",
    color: "Silver",
    brand: "Apple",
  },
  {
    id: 2,
    name: "Cell Phone",
    price: 800,
    imagePath: "https://i.ibb.co/D7NZDPk/headphones-a-1.webp",
    color: "Black",
    brand: "Samsung",
  },
  {
    id: 3,
    name: "Keyboard",
    price: 50,
    imagePath: "https://i.ibb.co/KzwMh9w/watch-3.webp",
    color: "Black",
    brand: "Microsoft",
  },
  {
    id: 4,
    name: "Mouse",
    price: 10,
    imagePath: "https://i.ibb.co/CQN3cCp/watch-2.webp",
    color: "Black",
    brand: "Microsoft",
  },
];
