import { Product } from "interfaces";

export const dummyProducts: Product[] = [
  {
    id: 0,
    name: "Surface",
    price: 1200,
    imagePath: "https://i.ibb.co/txhwSns/headphones-a-4.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 1,
    name: "MacBook Air",
    price: 999,
    imagePath: "https://i.ibb.co/CnzYPw1/headphones-c-1.webp",
    color: "Silver",
    brand: "Apple",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 2,
    name: "Cell Phone",
    price: 800,
    imagePath: "https://i.ibb.co/D7NZDPk/headphones-a-1.webp",
    color: "Black",
    brand: "Samsung",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 3,
    name: "Keyboard",
    price: 50,
    imagePath: "https://i.ibb.co/KzwMh9w/watch-3.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 4,
    name: "Mouse",
    price: 10,
    imagePath: "https://i.ibb.co/CQN3cCp/watch-2.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 5,
    name: "Surface",
    price: 1200,
    imagePath: "https://i.ibb.co/txhwSns/headphones-a-4.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 6,
    name: "MacBook Air",
    price: 999,
    imagePath: "https://i.ibb.co/CnzYPw1/headphones-c-1.webp",
    color: "Silver",
    brand: "Apple",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 7,
    name: "Cell Phone",
    price: 800,
    imagePath: "https://i.ibb.co/D7NZDPk/headphones-a-1.webp",
    color: "Black",
    brand: "Samsung",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 8,
    name: "Keyboard",
    price: 50,
    imagePath: "https://i.ibb.co/KzwMh9w/watch-3.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 9,
    name: "Mouse",
    price: 10,
    imagePath: "https://i.ibb.co/CQN3cCp/watch-2.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 10,
    name: "Surface",
    price: 1200,
    imagePath: "https://i.ibb.co/txhwSns/headphones-a-4.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 11,
    name: "MacBook Air",
    price: 999,
    imagePath: "https://i.ibb.co/CnzYPw1/headphones-c-1.webp",
    color: "Silver",
    brand: "Apple",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 12,
    name: "Cell Phone",
    price: 800,
    imagePath: "https://i.ibb.co/D7NZDPk/headphones-a-1.webp",
    color: "Black",
    brand: "Samsung",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 13,
    name: "Keyboard",
    price: 50,
    imagePath: "https://i.ibb.co/KzwMh9w/watch-3.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 14,
    name: "Mouse",
    price: 10,
    imagePath: "https://i.ibb.co/CQN3cCp/watch-2.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU Memory: 8GB or 16GB unified memoryStorage: 256GB, 512GB, 1TB, or 2TB SSDDisplay: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolutionTouch ID: Integrated Touch ID sensor for secure authentication and Apple PayKeyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangementPorts: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0Camera: 720p FaceTime HD cameraAudio: Stereo speakers with wide stereo sound, support for Dolby Atmos playback, and three-mic array with directional beamformingBattery life: Up to 15 hours of web browsing or up to 18 hours of video playbackDimensions: 11.97 x 8.36 x 0.63 inches (30.41 x 21.24 x 1.61 cm)Weight: 2.8 pounds (1.29 kg)",
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
];
