import { Product } from "interfaces";

export const dummyProducts: Product[] = [
  {
    id: 0,
    name: "Macbook Air",
    price: 1218.85,
    imagePath: "https://i.ibb.co/txhwSns/headphones-a-4.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 1,
    name: "MacBook Air",
    price: 999,
    imagePath: "https://i.ibb.co/CnzYPw1/headphones-c-1.webp",
    color: "Silver",
    brand: "Apple",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 2,
    name: "Cell Phone",
    price: 800,
    imagePath: "https://i.ibb.co/D7NZDPk/headphones-a-1.webp",
    color: "Black",
    brand: "Samsung",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 3,
    name: "Keyboard",
    price: 50,
    imagePath: "https://i.ibb.co/KzwMh9w/watch-3.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 4,
    name: "Mouse",
    price: 10,
    imagePath: "https://i.ibb.co/CQN3cCp/watch-2.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 5,
    name: "Surface",
    price: 1200,
    imagePath: "https://i.ibb.co/txhwSns/headphones-a-4.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 6,
    name: "MacBook Air",
    price: 999,
    imagePath: "https://i.ibb.co/CnzYPw1/headphones-c-1.webp",
    color: "Silver",
    brand: "Apple",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 7,
    name: "Cell Phone",
    price: 800,
    imagePath: "https://i.ibb.co/D7NZDPk/headphones-a-1.webp",
    color: "Black",
    brand: "Samsung",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 8,
    name: "Keyboard",
    price: 50,
    imagePath: "https://i.ibb.co/KzwMh9w/watch-3.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 9,
    name: "Mouse",
    price: 10,
    imagePath: "https://i.ibb.co/CQN3cCp/watch-2.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 10,
    name: "Surface",
    price: 1200,
    imagePath: "https://i.ibb.co/txhwSns/headphones-a-4.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 11,
    name: "MacBook Air",
    price: 999,
    imagePath: "https://i.ibb.co/CnzYPw1/headphones-c-1.webp",
    color: "Silver",
    brand: "Apple",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 12,
    name: "Cell Phone",
    price: 800,
    imagePath: "https://i.ibb.co/D7NZDPk/headphones-a-1.webp",
    color: "Black",
    brand: "Samsung",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 13,
    name: "Keyboard",
    price: 50,
    imagePath: "https://i.ibb.co/KzwMh9w/watch-3.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
  {
    id: 14,
    name: "Mouse",
    price: 10,
    imagePath: "https://i.ibb.co/CQN3cCp/watch-2.webp",
    color: "Black",
    brand: "Microsoft",
    description: "The MacBook Air is a sleek and stylish laptop that's perfect for people on the go. With its lightweight design and thin profile, it's easy to take with you wherever you go, whether you're heading to a coffee shop, a meeting, or a plane.",
    details: [
      {
        id: 0,
        detail: "Processor: Apple M1 chip with 8-core CPU and 7- or 8-core GPU",
      },
      {
        id: 1,
        detail: "Memory: 8GB or 16GB unified memory",
      },
      {
        id: 2,
        detail: "Storage: 256GB, 512GB, 1TB, or 2TB SSD",
      },
      {
        id: 3,
        detail: "Display: 13.3-inch Retina display with True Tone technology, 2560-by-1600 resolution",
      },
      {
        id: 4,
        detail: "Touch ID: Integrated Touch ID sensor for secure authentication and Apple Pay",
      },
      {
        id: 5,
        detail: "Keyboard: Backlit Magic Keyboard with 65 keys (US) or 66 keys (ISO), including four arrow keys in an inverted-T arrangement",
      },
      {
        id: 6,
        detail: "Ports: Two Thunderbolt 3 (USB-C) ports with support for charging, DisplayPort, Thunderbolt (up to 40Gb/s), and USB 3.1 Gen 2 (up to 10Gb/s)",
      },
      {
        id: 7,
        detail: "Wireless: Wi-Fi 6 (802.11ax) and Bluetooth 5.0",
      },
    ],
    category: "Electronics",
    rating: 4.5,
    reviews: [
      {
        id: 0,
        title: "Excellent product",
        name: "John Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod\ labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        date: "2021-01-01",
      },
      {
        id: 1,
        title: "Excellent product",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 4.5,
        name: "Jane Doe",
        date: "2021-01-01",
      },
      {
        id: 2,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
      {
        id: 3,
        title: "Excellent product",
        name: "Jane Doe",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
        rating: 3.5,
        date: "2-3-2023",
      },
    ],
    isAvailable: true,
  },
];
